### ISSUE TITLE
ZipArchive constructor

### ISSUE THREAD

**Issue by tagcode** [soukoku/FileProviders.Zip#1]
Hi,

Could you make a constructor that takes in ZipArchive, so that the caller can provide an open file. 

The current constructors make a memory snapshot of the whole file, which is not necessary in some use cases. And it's limited to 2GB.

My suggestion:

public ZipFileProvider(ZipArchive zipArchive, bool disposeArchiveWithFileProvider = true) { ... }

The fileprovider would also also implement IDisposable which would dispose the underlying zipArchive if that flag was set to true. You could add a comment that disposing of the ZipFileProvider is only necessary when used with that specific constructor and with true flag.

**Comment by soukoku** [comment]
This is not possible because ZipArchive is not thread safe. At best I can only make the constructor that takes a file path not load entire file in memory.

**Comment by tagcode** [comment]
Oh, I didn't know that. Well you could synchronize the ZipArchive calls, making it thread-safe, but not thread-scalable.

Filepath constructor would be very nice too. But, how do you intend to implement it? You'd need a new ZipArchive for each thread.

**Comment by soukoku** [comment]
It currently does creates a ZipArchive object when getting a file entry :scream:.  Was the best way I could make it work. Just need to open a file stream on top of that if using file path constructor.
